ALTER TABLE buildings
    ADD COLUMN layout_x DOUBLE PRECISION,
    ADD COLUMN layout_y DOUBLE PRECISION,
    ADD COLUMN layout_width DOUBLE PRECISION,
    ADD COLUMN layout_height DOUBLE PRECISION;

ALTER TABLE floors
    ADD COLUMN layout_x DOUBLE PRECISION,
    ADD COLUMN layout_y DOUBLE PRECISION,
    ADD COLUMN layout_width DOUBLE PRECISION,
    ADD COLUMN layout_height DOUBLE PRECISION;

ALTER TABLE spaces
    ADD COLUMN layout_x DOUBLE PRECISION,
    ADD COLUMN layout_y DOUBLE PRECISION,
    ADD COLUMN layout_width DOUBLE PRECISION,
    ADD COLUMN layout_height DOUBLE PRECISION;
