package com.dwellio.domain.enums;

public enum NotificationType {
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,
    COMPLAINT_CREATED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_RESOLVED,
    COMPLAINT_REOPENED,
    ANNOUNCEMENT_PUBLISHED,
    OCCUPANCY_ALLOCATED,
    OCCUPANCY_TRANSFERRED,
    REVIEW_REPORTED,
    SYSTEM
}
